version: "3.8"

services:
  backend-py:
    build: ./backend-py
    ports:
      - "50051:50051"  # gRPC service
      - "8000:8000"  # Metrics endpoint for Prometheus
    environment:
      - PROMETHEUS_METRICS=true
    networks:
      - backend_network

  backend-ts:
    build: ./backend-ts
    ports:
      - "4000:3000"  # API Service
      - "4001:3001"  # Metrics endpoint for Prometheus
    networks:
      - backend_network
networks:
  backend_network:
    driver: bridge
