version: "3.8"

services:
  backend-py:
    build: ./backend-py
    ports:
      - "50051:50051"  # gRPC service
      - "8000:8000"  # Metrics endpoint for Prometheus
    environment:
      - PROMETHEUS_METRICS=true
    env_file:
      - ./backend-py/.env
    networks:
      - backend_network
    restart: always
      
networks:
  backend_network:
    driver: bridge
  
