# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: algorithm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'algorithm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61lgorithm.proto\x12\talgorithm\",\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\t\"0\n\x0eUploadResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"V\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\"!\n\x0f\x44ownloadRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"$\n\x11\x46ileChunkResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"9\n\x15\x43onfirmDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb9\x02\n\x10\x41lgorithmService\x12?\n\nUploadFile\x12\x14.algorithm.FileChunk\x1a\x19.algorithm.UploadResponse(\x01\x12I\n\x0cGetJobStatus\x12\x1b.algorithm.JobStatusRequest\x1a\x1c.algorithm.JobStatusResponse\x12J\n\x0c\x44ownloadFile\x12\x1a.algorithm.DownloadRequest\x1a\x1c.algorithm.FileChunkResponse0\x01\x12M\n\rConfirmDelete\x12\x1a.algorithm.DownloadRequest\x1a .algorithm.ConfirmDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=30
  _globals['_FILECHUNK']._serialized_end=74
  _globals['_UPLOADRESPONSE']._serialized_start=76
  _globals['_UPLOADRESPONSE']._serialized_end=124
  _globals['_JOBSTATUSREQUEST']._serialized_start=126
  _globals['_JOBSTATUSREQUEST']._serialized_end=160
  _globals['_JOBSTATUSRESPONSE']._serialized_start=162
  _globals['_JOBSTATUSRESPONSE']._serialized_end=248
  _globals['_DOWNLOADREQUEST']._serialized_start=250
  _globals['_DOWNLOADREQUEST']._serialized_end=283
  _globals['_FILECHUNKRESPONSE']._serialized_start=285
  _globals['_FILECHUNKRESPONSE']._serialized_end=321
  _globals['_CONFIRMDELETERESPONSE']._serialized_start=323
  _globals['_CONFIRMDELETERESPONSE']._serialized_end=380
  _globals['_ALGORITHMSERVICE']._serialized_start=383
  _globals['_ALGORITHMSERVICE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
